# Generated by Django 6.0.7 on 2026-08-11 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('custom_field', models.CharField(blank=True, max_length=255, null=True)),
                ('image_front', models.ImageField(upload_to='scans/inputs/')),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('processed_3d_model', models.FileField(blank=True, null=True, upload_to='scans/outputs/')),
                ('calibration_type', models.CharField(choices=[('USER_CIRCUMFERENCE', 'User Head Circumference (cm)'), ('USER_IPD', 'User IPD (cm)'), ('AUTO_ESTIMATE', 'Auto Estimate')], default='USER_CIRCUMFERENCE', max_length=30)),
                ('calibration_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eye_to_eye', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ear_to_ear', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('head_width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('head_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('head_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('head_circumference_A', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('forehead_to_back_B', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cross_measurement_C', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('under_chin_D', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eyebrow_to_earlobe_E', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eye_corner_to_ear_F', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ear_height_G', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ear_width_H', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cheek_guard_clearance_L', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cheek_guard_height_M', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cheek_guard_width_N', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/inputs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='scans.scan')),
            ],
        ),
    ]
